# Generated by Django 5.0 on 2024-01-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_discount_order_remove_tax_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdiscount",
            name="amount",
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordertax",
            name="rate",
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
    ]
